name: Build And Push To Dockerhub

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: build image
        run: make build

      - name: tag remote
        run: make tag-remote

      - name: login into dockerhub
        run: make login

      - name: push image
        run: make push
