name: Build And Push To Dockerhub

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dockerhub_env
    env:
      DOCKERHUB_USERNAME: ${{vars.DOCKERHUB_USERNAME}}
      REPOSITORY_NAME: ${{vars.REPOSITORY_NAME}}
      DOCKERHUB_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
    steps:
      - uses: actions/checkout@v4

      - name: build image
        run: make build

      - name: tag remote
        run: make tag-remote

      - name: push image
        run: make push
